syntax = "proto3";

package tieba;

option java_package = "com.huanchengfly.tieba.post.api.models.protos";

import "AdInfo.proto";
import "Abstract.proto";
import "Agree.proto";
import "AlaLiveInfo.proto";
import "DislikeInfo.proto";
import "HotTWThreadInfo.proto";
import "Media.proto";
import "OriginThreadInfo.proto";
import "PbContent.proto";
import "PollInfo.proto";
import "PostList.proto";
import "SimpleForum.proto";
import "TiebaPlusAd.proto";
import "Topic.proto";
import "User.proto";
import "VideoInfo.proto";
import "Voice.proto";
import "VoiceRoom.proto";
import "Zan.proto";
import "ZhiBoInfoTW.proto";

message ThreadInfo {
  int64 id = 1;
  int64 threadId = 2;
  string title = 3;
  int32 replyNum = 4;
  int32 viewNum = 5;
  string lastTime = 6;
  int32 lastTimeInt = 7;
  int32 threadTypes = 8;
  int32 isTop = 9;
  int32 isGood = 10;
  int32 is_vote = 11;
  int32 is_bakan = 12;
  int32 is_protal = 13;
  int32 is_meizhi = 14;
  int32 is_voice_thread = 15;
  int32 is_activity = 16;
  int32 is_notice = 17;
  User author = 18;
  User lastReplyer = 19;
  int32 commentNum = 20;
  repeated Abstract _abstract = 21;
  repeated Media media = 22;
  repeated Voice voice_info = 23;
  string meizhi_pic = 24;
  int32 thread_type = 26;
  int64 forumId = 27;
  string forumName = 28;
  string live_post_type = 29;
  int32 is_livepost = 30;
  int32 show_commented = 31;
  string click_url = 32;
  string video = 33;
  string video_swf = 34;
  string video_cover = 35;
  string video_id = 36;
  string video_mobile_url = 37;
  int32 isNoTitle = 38;
  int32 is_bub = 39;
  int64 firstPostId = 40;
  Zan zan = 41;
  int32 is_global_top = 42;
  int32 is_pic = 43;
  repeated PostList post_list = 44;
  int32 createTime = 45;
  int32 repost_num = 46;
  Topic topic = 47;
  int32 has_commented = 48;
  string from = 49;
  int32 collectStatus = 50;
  string collectMarkPid = 51;
  int64 post_id = 52;
  int32 time = 53;
  int32 isMemberTop = 54;
  int64 authorId = 56;
  uint32 is_ad = 59;
  string ecom = 60;
  string pids = 61;
  int32 hot_weight = 66;
  string livecover_src = 67;
  int32 storecount = 68;
  int32 post_num = 69;
  HotTWThreadInfo hotTWInfo = 71;
  ZhiBoInfoTW twzhibo_info = 72;
  string category_name = 73;
  PollInfo poll_info = 74;
  int32 is_novel = 76;
  int32 is_novel_thank = 77;
  int32 is_novel_reward = 78;
  optional VideoInfo videoInfo = 79;
  int32 push_end_time = 80;
  uint32 is_copythread = 81;
  uint32 operator_flag = 82;
  uint32 pic_num = 84;
  int32 is_godthread_recommend = 85;
  AdInfo video_ad_info = 110;
  repeated PbContent richTitle = 111;
  repeated PbContent richAbstract = 112;
  optional AlaLiveInfo ala_info = 113;
  repeated DislikeInfo dislikeInfo = 120;
  int32 agreeNum = 124;
  Agree agree = 126;
  int64 shareNum = 135;
  OriginThreadInfo origin_thread_info = 141;
  repeated PbContent firstPostContent = 142;
  int32 is_share_thread = 143;
  int32 isTopic = 148;
  string topicUserName = 149;
  string topicH5Url = 150;
  SimpleForum forumInfo = 155;
  string tShareImg = 159;
  string nid = 164;
  int32 tabId = 175;
  string tabName = 176;
  int32 isDeleted = 181;
  int32 hotNum = 182;
  VoiceRoom voice_room = 199;
  TiebaPlusAd tiebaplus_ad = 201;
  int32 poll_style = 256;
}